DICIONARIO_5_LETRAS = {
    "AMIGO": "Pessoa com quem se tem uma relação de afeto e confiança.",
    "APOIO": "Ação de ajudar, sustentar ou favorecer alguém.",
    "ARROZ": "Cereal amplamente consumido como alimento básico.",
    "AVIAO": "Aeronave mais pesada que o ar, movida por motores.",
    "ATLAS": "Coleção de mapas geográficos ou conjunto de dados.",
    "BANCO": "Assento para várias pessoas ou instituição financeira.",
    "BARCO": "Embarcação para navegação em águas.",
    "BEIJO": "Toque com os lábios em sinal de afeto ou saudação.",
    "BOTAO": "Peça para fechar roupas ou acionar um dispositivo.",
    "BRAVO": "Pessoa corajosa, valente ou que está com raiva.",
    "BRISA": "Vento leve, suave e fresco.",
    "CAIXA": "Recipiente de formato geralmente cúbico ou retangular.",
    "CAMPO": "Área de terra aberta ou espaço para prática esportiva.",
    "CANTA": "Ação de produzir sons melodiosos com a voz.",
    "CARRO": "Veículo automotor de quatro rodas para transporte.",
    "CARTA": "Mensagem escrita enviada a alguém por correio.",
    "CERTO": "Aquilo que é correto, verdadeiro ou sem erros.",
    "CHAVE": "Instrumento usado para abrir ou fechar fechaduras.",
    "CHUVA": "Precipitação de água líquida caindo das nuvens.",
    "CINZA": "Resíduo da combustão; cor intermediária entre preto e branco.",
    "CORPO": "Estrutura física e material de um ser vivo.",
    "CORRE": "Ação de deslocar-se rapidamente a pé.",
    "CUSTO": "Preço pago ou valor gasto para obter algo.",
    "DANCA": "Sequência de movimentos corporais ao ritmo da música.",
    "DENTE": "Estrutura dura na boca usada para mastigar alimentos.",
    "DISCO": "Objeto circular e achatado usado para gravar dados ou música.",
    "DORME": "Ação de repousar em estado de sono.",
    "DRAMA": "Situação tensa, conflituosa ou peça teatral.",
    "FESTA": "Comemoração ou reunião de pessoas para se divertirem.",
    "FORTE": "Pessoa ou objeto com grande força, resistência ou poder.",
    "FRUTA": "Alimento comestível e adocicado produzido por plantas.",
    "FUNDO": "Parte mais baixa de um recipiente ou espaço.",
    "GENTE": "Conjunto de pessoas ou seres humanos.",
    "GRUPO": "Conjunto de pessoas ou coisas reunidas.",
    "HOTEL": "Estabelecimento que oferece hospedagem temporária.",
    "IDEIA": "Representação mental, pensamento ou conceito.",
    "JOVEM": "Pessoa que está na fase da juventude.",
    "LEITE": "Líquido nutritivo branco produzido pelas fêmeas mamíferas.",
    "LENTO": "Que se move com pouca velocidade; demorado.",
    "LIVRO": "Objeto composto por folhas impressas e reunidas.",
    "MAGIA": "Arte de produzir fenômenos extraordinários.",
    "MARCA": "Sinal, vestígio ou identificação de uma empresa.",
    "METRO": "Unidade fundamental de medida de comprimento.",
    "MONTE": "Elevação natural do terreno; pilha de coisas.",
    "MUNDO": "O planeta Terra ou a totalidade da existência humana.",
    "NAVIO": "Grande embarcação destinada ao transporte marítimo.",
    "NOITE": "Período entre o pôr e o nascer do sol.",
    "NORTE": "Um dos quatro pontos cardeais da bússola.",
    "NUVEM": "Massa visível de gotas de água suspensas no ar.",
    "PADRE": "Sacerdote da Igreja Católica.",
    "PEDRA": "Matéria mineral sólida e dura.",
    "PEIXE": "Animal vertebrado aquático que respira por guelras.",
    "PENSA": "Ação de refletir, raciocinar ou formar ideias.",
    "PIANO": "Instrumento musical de teclado e cordas percutidas.",
    "PLANO": "Projeto, esquema ou superfície sem elevações.",
    "PODER": "Capacidade ou autoridade para realizar algo.",
    "PONTO": "Sinal gráfico ou local específico em um espaço.",
    "PORTA": "Abertura para entrada e saída de um ambiente.",
    "PRATO": "Utensílio raso ou fundo usado para servir refeições.",
    "PRETO": "A cor mais escura; ausência total de luz.",
    "PROVA": "Exame para testar conhecimentos ou evidência de um fato.",
    "RADIO": "Aparelho que recebe transmissões de ondas sonoras.",
    "RAIVA": "Sentimento de grande irritação ou fúria.",
    "REGRA": "Norma estabelecida para orientar o comportamento.",
    "RISCO": "Possibilidade de perigo ou linha desenhada numa superfície.",
    "ROUPA": "Peças de vestuário usadas para cobrir o corpo.",
    "SABOR": "Sensação percebida pelo paladar ao comer algo.",
    "SAGAZ": "Pessoa astuta, esperta e de raciocínio rápido.",
    "SAUDE": "Estado de bem-estar físico, mental e social.",
    "SONHO": "Imagens e pensamentos durante o sono ou um grande desejo.",
    "SORTE": "Acontecimento favorável atribuído ao acaso.",
    "TEMPO": "Duração dos fatos ou condições atmosféricas.",
    "TERRA": "O planeta onde vivemos ou o solo onde pisamos.",
    "TEXTO": "Conjunto de palavras organizadas em uma mensagem escrita.",
    "TIGRE": "Grande mamífero carnívoro da família dos felinos.",
    "TORRE": "Construção alta que se destaca em uma estrutura.",
    "UNIAO": "Ação de juntar duas ou mais coisas; aliança.",
    "VALOR": "Preço, importância ou qualidade atribuída a algo.",
    "VENTO": "Ar em movimento natural na atmosfera.",
    "VERDE": "Cor característica das folhas das plantas.",
    "VERBA": "Quantia em dinheiro destinada a um fim específico.",
    "VIGOR": "Força física, energia e entusiasmo.",
}